version: '2'
services:
  django:
    build: .
    depends_on:
      - db
    volumes:
      - "./static:/home/build/static"
      - "./media:/home/build/media"
    restart: always

  nginx:
    build: ./docker/nginx
    depends_on:
      - django
    ports:
      - "82:80"
    volumes:
      - "./static:/home/build/static"
      - "./media:/home/build/media"
    restart: always

  db:
    build: ./docker/db
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: pykrd
      POSTGRES_USER: pykrd
      POSTGRES_PASSWORD: pykrd
    restart: always
