# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='post'),
        ),
    ]
