# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
