# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(upload_to='series')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Series'),
        ),
    ]
