# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
