# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20160808_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
